export type tBank =
	| 'BBVA Bancomer'
	| 'Citibanamex'
	| 'Santander México'
	| 'HSBC México'
	| 'Banorte'
	| 'Scotiabank'
	| 'Inbursa'
	| 'Banco Azteca'
	| 'Banco del Bajío (BanBajío)'
	| 'Banregio'
	| 'Banco Multiva'
	| 'Afirme'
	| 'Intercam Banco'
	| 'BanCoppel'
	| 'Nu'
	| 'RappiCard'
	| 'Efectivo'
